---
- hosts: second_instance
  vars_files:
    - versions_config.yml
  become: yes 
  roles:
    - common
    - docker
    - docker-compose
    - gitlab
    - mysql
    - start_app
    - drone
    - drone-cli

# Associate further roles to servers in specific group in this file...

...
