---
# tasks file for drone

# Copyright (C) 2019 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: "create /home/{{ ansible_user_id }}/drone"
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - { path: "/home/{{ ansible_user_id }}/drone/drone-server" }
    - { path: "/home/{{ ansible_user_id }}/drone/drone-agent" }
  tags:
    - drone 

- name: "template files into /home/{{ ansible_user_id }}/drone"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    force: yes
  with_items:
    - { src: "templates/README.j2", dest: "/home/{{ ansible_user_id }}/drone/README.MD" }
    - { src: "templates/docker-compose.j2", dest: "/home/{{ ansible_user_id }}/drone/docker-compose.yml" }
    - { src: "templates/drone-server/Dockerfile.j2", dest: "/home/{{ ansible_user_id }}/drone/drone-server/Dockerfile" }
    - { src: "templates/drone-server/dockerfile_build.j2", dest: "/home/{{ ansible_user_id }}/drone/drone-server/dockerfile_build.sh" }
    - { src: "templates/drone-agent/Dockerfile.j2", dest: "/home/{{ ansible_user_id }}/drone/drone-agent/Dockerfile" }
    - { src: "templates/drone-agent/dockerfile_build.j2", dest: "/home/{{ ansible_user_id }}/drone/drone-agent/dockerfile_build.sh" }
  tags:
    - drone 

- name: make dockerfile_build.sh scripts executable
  become: yes
  file: 
    path: "{{ item.path }}"
    mode: "u=rwx,g=r,o=r"  
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items:
    - { path: "/home/{{ ansible_user_id }}/drone/drone-server/dockerfile_build.sh" }
    - { path: "/home/{{ ansible_user_id }}/drone/drone-agent/dockerfile_build.sh" }
  tags:
    - drone 

- name: "build nemonik/agent:{{ drone_version }} and nemonik/drone:{{ drone_version }} docker images"
  become: yes
  docker_image:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
  with_items:
    - { path: "/home/{{ ansible_user_id }}/drone/drone-agent", name: "nemonik/agent:{{ drone_version }}" }
    - { path: "/home/{{ ansible_user_id }}/drone/drone-server", name: "nemonik/drone:{{ drone_version }}" }
  tags:
    - drone

- debug:
    msg: "Drone will need to be stood up by hand as per the README.md"
  tags:
    - drone
