---
# tasks file for docker
# Based on https://docs.docker.com/install/linux/docker-ce/centos/

# Copyright (C) 2019 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>

- name: uninstall old versions of docker
  become: yes
  yum:
    name: ['docker', 'docker-client', 'docker-client-latest', 'docker-common', 'docker-latest', 'docker-latest-logrotate', 'docker-logrotate', 'docker-engine']
    state: absent
  tags:
    - docker


- name: install docker using amazon-linux-extras
  command: amazon-linux-extras install docker
  become: yes

- name: start docker service 
  service:
    name: docker

- name: ensure docker group exists
  become: yes
  group:
    name: docker
    state: present
  tags:
    - docker

- name: add ec2-user and root to docker group
  command: usermod -a -G docker {{ item }}
  with_items:
    - ec2-user
    - root

#- name: uninstall docker-py
#  pip:
#    name: docker-py
#    state: absent
