---
# tasks file for docker-registry

# Copyright (C) 2019 Michael Joseph Walsh - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the the license.
#
# You should have received a copy of the license with
# this file. If not, please email <mjwalsh@nemonik.com>
 
- name: "copy to docker-registry files to /home/{{ ansible_user_id }}/docker-registry"
  become: yes
  copy:
    src: files/
    dest: /home/{{ ansible_user_id }}/docker-registry
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - docker-registry 

- name: "template files into /home/{{ ansible_user_id }}/docker-registry"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"   
  with_items:
    - { src: "templates/README.j2", dest: "/home/{{ ansible_user_id }}/docker-registry/README.MD" }
    - { src: "templates/Dockerfile.j2", dest: "/home/{{ ansible_user_id }}/docker-registry/Dockerfile" }
    - { src: "templates/dockerfile_build.j2", dest: "/home/{{ ansible_user_id }}/docker-registry/dockerfile_build.sh" }
    - { src: "templates/docker-compose.j2", dest: "/home/{{ ansible_user_id }}/docker-registry/docker-compose.yml" }
  tags:
    - docker-registry 

- name: "make /home/{{ ansible_user_id }}/docker-registry/dockerfile_build.sh executable"
  become: yes
  file: 
    path: "/home/{{ ansible_user_id }}/docker-registry/dockerfile_build.sh"
    mode: "u=rwx,g=r,o=r"  
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  tags:
    - docker-registry 

- name: "build nemonik/registry:{{ registry_version }} docker image "
  become: yes
  docker_image:
    path: "/home/{{ ansible_user_id }}/docker-registry"
    name: "nemonik/registry:{{ registry_version }}"
    buildargs:
      http_proxy: "{{ http_proxy|default('') }}"
      HTTP_PROXY: "{{ http_proxy|default('') }}"
      https_proxy: "{{ https_proxy|default('') }}"
      HTTPS_PROXY: "{{ https_proxy|default('') }}"
      NO_PROXY: "{{ no_proxy|default('') }}"
      no_proxy: "{{ no_proxy|default('') }}" 
  tags:
    - docker-registry 

- name: spin up private docker-registry via docker-compose
  become: yes
  docker_service:
    build: no
    debug: yes
    project_src: "/home/{{ ansible_user_id }}/docker-registry"
  tags:
    - docker-registry 